* noon.eval

The =noon.eval= namespace is leveraging the great =babashka.sci= library to bring different noon parts together into a friendly user interface.
More precisely, using =noon.eval= top forms is similar to being in a namespace with those requirements.

#+begin_src clojure
(ns my.namespace
  (:require [noon.updates :refer :all]
            [noon.events :as events :refer [ef_ efn]]
            [noon.score :as score :refer [score sf_ sfn e->s]]
            [noon.output :as out :refer [noon play]]
            [noon.lib.harmony :as h]
            [noon.lib.melody :as m]
            [noon.lib.rythmn :as r]
            [noon.numbers :refer [mul div add sub]]
            [noon.midi :as midi]
            [noon.utils.misc :as u]
            [noon.constants :as constants]
            [noon.utils.pseudo-random :as rand]
            ...
            ))
#+end_src

It also helps to support the clojurescript side of things where some restrictions are taking place.
The =:refer :all= syntax is not possible in cljs, and the =noon.updates= namespace is containing a lot of vars that you probably  don't want to write or prefix.

The three main forms that =noon.eval= exposes (=score= , =play= , =noon=) are macros mainly for the sake of this.
Under this, the noon API consists mainly of functions dealing with data, the two main underlying forms (=noon.output/noon=, =noon.score/score=) are functions and you can do everything you want using them directly.
