name: Update README

on:
  workflow_run:
     workflows: ["Tests"]
     types:
       - completed

jobs:
  update-readme:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Run the update script
        run: ./scripts/update_readme.sh

      - name: Commit changes
        run: |
          git add README.md
          git commit -m "Update README with latest commit hash"
          git push
